document.write("<p>Nombre del navegador: ");
document.write(infoNavegador.nombre);
document.write(" - Idioma: ");
document.write(infoNavegador.idioma);
document.write(" - Version: ");
document.write(infoNavegador.version);
document.write(" - Plataforma: ");
document.write(infoNavegador.plataforma);
document.write(" - Vendedor: ");
document.write(infoNavegador.vendedor);
document.write(" - Agente: ");
document.write(infoNavegador.agente);
document.write(" - Java activo: ");
document.write(infoNavegador.javaActivo);
document.write("</p>");